In [ ]:
# 구글 드라이브를 마운트 합니다.

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
%cd '/content/drive/MyDrive/Miniproject_No_1/0.Code&Data/datas'

/content/drive/.shortcut-targets-by-id/1aC_8L2n1X-pOPdZ-Mwkmrq2_Ogm1qk11/Miniproject_No_1/0.Code&Data/datas

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [1]:
!pip install pandas==1.2.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pandas==1.2.0
  Downloading pandas-1.2.0-cp39-cp39-manylinux1_x86_64.whl (9.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 36.8 MB/s eta 0:00:00
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.9/dist-packages (from pandas==1.2.0) (2022.7.1)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.9/dist-packages (from pandas==1.2.0) (1.22.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.9/dist-packages (from pandas==1.2.0) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.7.3->pandas==1.2.0) (1.15.0)
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 1.4.4
    Uninstalling pandas-1.4.4:
      Successfully uninstalled pandas-1.4.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xarray 2022.12.0 requires pandas>=1.3, but you have pandas 1.2.0 which is incompatible.
plotnine 0.10.1 requires pandas>=1.3.5, but you have pandas 1.2.0 which is incompatible.
mizani 0.8.1 requires pandas>=1.3.5, but you have pandas 1.2.0 which is incompatible.
arviz 0.15.1 requires pandas>=1.3.0, but you have pandas 1.2.0 which is incompatible.
Successfully installed pandas-1.2.0

In [ ]:
a = pd.read_csv('/content/drive/MyDrive/Miniproject_No_1/0.Code&Data/datas/경쟁업체/소상공인시장진흥공단_상가(상권)정보_서울_202212.csv')
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 377724 entries, 0 to 377723
Data columns (total 39 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   상가업소번호     377724 non-null  int64
 1   상호명        377724 non-null  object
 2   지점명        63169 non-null   object
 3   상권업종대분류코드  377724 non-null  object
 4   상권업종대분류명   377724 non-null  object
 5   상권업종중분류코드  377724 non-null  object
 6   상권업종중분류명   377724 non-null  object
 7   상권업종소분류코드  377724 non-null  object
 8   상권업종소분류명   377724 non-null  object
 9   표준산업분류코드   351543 non-null  object
 10  표준산업분류명    351543 non-null  object
 11  시도코드       377724 non-null  int64
 12  시도명        377724 non-null  object
 13  시군구코드      377724 non-null  int64
 14  시군구명       377724 non-null  object
 15  행정동코드      377724 non-null  int64
 16  행정동명       377724 non-null  object
 17  법정동코드      377724 non-null  int64
 18  법정동명       377724 non-null  object
 19  지번코드       377724 non-null  int64
 20  대지구분코드     377724 non-null  int64
 21  대지구분명      377724 non-null  object
 22  지번본번지      377724 non-null  int64
 23  지번부번지      299122 non-null  float64
 24  지번주소       377724 non-null  object
 25  도로명코드      377724 non-null  int64
 26  도로명        377724 non-null  object
 27  건물본번지      377724 non-null  int64
 28  건물부번지      50597 non-null   float64
 29  건물관리번호     377724 non-null  object
 30  건물명        187667 non-null  object
 31  도로명주소      377724 non-null  object
 32  구우편번호      377724 non-null  int64
 33  신우편번호      377688 non-null  float64
 34  동정보        44057 non-null   object
 35  층정보        231453 non-null  object
 36  호정보        0 non-null       float64
 37  경도         377724 non-null  float64
 38  위도         377724 non-null  float64
dtypes: float64(6), int64(11), object(22)
memory usage: 112.4+ MB

In [ ]:
%pwd

'/content'