In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import folium

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
import requests
import json
import numpy as np

In [6]:
%pwd

'/content'

In [ ]:
pd.read_csv('/content/drive/MyDrive/0.Code&Data/datas/경쟁업체/서울시 일반음식점 인허가 정보.csv',encoding="utf-8-sig")

In [12]:
df_sales = pd.read_csv('/content/drive/MyDrive/0.Code&Data/datas/임대료/지역별평균매출액.csv',encoding='CP949')

In [13]:
df_rent = pd.read_csv('/content/drive/MyDrive/0.Code&Data/datas/임대료/지역별평균임대료.csv',encoding='CP949')

In [15]:
chicken_sales= pd.read_csv('/content/drive/MyDrive/0.Code&Data/datas/임대료/치킨집+규모별+면적(3.3㎡)당+매출액_2019.csv')
chicken_sales

   생활밀접업종별(1)  생활밀접업종별(2)      2019  2019.1  2019.2  2019.3  2019.4
0  생활밀접업종별(1)  생활밀접업종별(2)  16.5㎡ 이하  33㎡ 이하  66㎡ 이하  99㎡ 이하  99㎡ 초과
1         서울시          소계       239     190     278     298     343
2         외식업          소계        94     118     184     249     333
3         외식업       치킨전문점       128     185     248     298     387

In [16]:
chicken_sales.iloc[1:]

  생활밀접업종별(1) 생활밀접업종별(2) 2019 2019.1 2019.2 2019.3 2019.4
1        서울시         소계  239    190    278    298    343
2        외식업         소계   94    118    184    249    333
3        외식업      치킨전문점  128    185    248    298    387

In [18]:
chicken_sales[['16.5㎡ 이하','33㎡ 이하','66㎡ 이하']]= chicken_sales[['16.5㎡ 이하','33㎡ 이하','66㎡ 이하']].astype(int)

KeyError: ignored

In [ ]:
chicken_sales.loc[0]
chicken_sales.columns = chicken_sales.loc[0]
chicken_sales = chicken_sales.iloc[1:]

In [ ]:
chicken_sales = chicken_sales.iloc[1:]

서울시 상가규모별 상가수  
16.5㎡ 이하: 38,020개  
16.5㎡ 초과 ~ 33㎡ 이하: 65,793개  
33㎡ 초과 ~ 66㎡ 이하: 67,124개  
66㎡ 초과 ~ 99㎡ 이하: 63,618개  
99㎡ 초과: 37,264개

In [ ]:
#규모별 평균 면적이랑 상가 수 곱해서 총합이랑 나눠서 평균 매출 나타냄
chicken_sales['배달전문'] = [138.579,197.06]
chicken_sales['홀매장'] = [280.028,330.875]

In [ ]:
chicken_sales.drop(['16.5㎡ 이하',	'33㎡ 이하',	'66㎡ 이하',	'99㎡ 이하',	'99㎡ 초과'],axis =1, inplace=True)

In [ ]:
chicken_sales # 치킨집이 매출이 좋네?

0 생활밀접업종별(1) 생활밀접업종별(2)     배달전문      홀매장
2        외식업         소계  138.579  280.028
3        외식업      치킨전문점  197.060  330.875

In [ ]:
df_sales.drop('Unnamed: 0',axis = 1,inplace=True)

In [ ]:
df_rent.drop('Unnamed: 0',axis = 1,inplace=True)

In [ ]:
df_sales_gu = df_sales.groupby('구').mean()

In [ ]:
df_sales_dong = df_sales.groupby('동명').mean()

In [ ]:
df_rent_dong = df_rent.groupby('동명').mean()

In [ ]:
df_rent_gu = df_rent.groupby('구').mean()

In [ ]:
df_rent_gu

         평균임대료
구
강남구   6.283158
강동구   5.585000
강북구   4.510000
강서구   4.767778
관악구   4.861429
광진구   5.481667
구로구   5.016667
금천구   3.543333
노원구   7.980000
도봉구   5.760000
동대문구  5.007500
동작구   5.131667
마포구   5.560000
서대문구  5.092500
서초구   4.638750
성동구   4.157500
성북구   4.912500
송파구   5.648750
양천구   5.135000
영등포구  6.016667
용산구   5.081429
은평구   6.245000
종로구   5.720000
중구    6.720833
중랑구   3.935000